# Generated by Django 4.0.6 on 2024-07-24 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_billrequest_completed_time_billrequest_is_completed'),
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblratings',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
    ]
