# Generated by Django 4.0.6 on 2024-07-09 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customergooglelogin_delete_customerlogin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customergooglelogin',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.customer'),
        ),
        migrations.AlterField(
            model_name='customergooglelogin',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customergooglelogin',
            name='google_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customernormallogin',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.customer'),
        ),
        migrations.AlterField(
            model_name='customernormallogin',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
