# Generated by Django 4.0.6 on 2024-07-12 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_customer_cardno_alter_customer_country_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerGooglelogin',
        ),
    ]
