# Generated by Django 4.0.6 on 2024-07-08 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('sorting_order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('item_name', models.CharField(max_length=255)),
                ('group', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('outlet', models.CharField(max_length=255)),
                ('discount_exempt', models.BooleanField(default=False)),
                ('is_promotional', models.BooleanField(default=False)),
                ('is_todayspecial', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
