# Generated by Django 4.0.6 on 2024-07-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menu_image_bytes'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='slug',
            field=models.SlugField(null=True, verbose_name='Product Slug'),
        ),
    ]
