# Generated by Django 4.0.6 on 2024-07-22 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_menutype_menu_menutype'),
    ]

    operations = [
        migrations.AddField(
            model_name='menutype',
            name='discount_percentage',
            field=models.FloatField(default=0.0),
        ),
    ]
