# Generated by Django 4.0.6 on 2024-07-22 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_alter_menu_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menutype',
            name='discount_percentage',
        ),
    ]
