# Generated by Django 4.0.6 on 2024-07-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_remove_menutype_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='promotional_price',
            field=models.FloatField(default=0.0),
        ),
    ]
