# Generated by Django 4.0.6 on 2024-07-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_menu_promotional_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlagMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_same_menu_for_multiple_outlet', models.BooleanField(default=True)),
            ],
        ),
    ]
