# Generated by Django 4.0.6 on 2024-07-25 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_flagmenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='flagmenu',
            name='autoaccept',
            field=models.BooleanField(default=False),
        ),
    ]
