# Generated by Django 4.0.6 on 2024-07-25 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_flagmenu_autoaccept'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flagmenu',
            old_name='autoaccept',
            new_name='autoaccept_order',
        ),
    ]
