# Generated by Django 4.0.6 on 2024-07-09 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderDetais',
            new_name='OrderDetails',
        ),
    ]
