# Generated by Django 4.0.6 on 2024-07-09 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_orderdetais_orderdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='outlet',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
