# Generated by Django 4.0.6 on 2024-07-19 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_outlet_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='modification',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
