# Generated by Django 4.0.6 on 2024-07-22 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_billrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='billrequest',
            name='outlet',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
