# Generated by Django 4.0.6 on 2024-07-22 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_billrequest_outlet'),
    ]

    operations = [
        migrations.AddField(
            model_name='billrequest',
            name='completed_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='billrequest',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
